"""Add remarks to exams

Revision ID: 822e56412bd4
Revises: 
Create Date: 2023-07-04 17:27:26.744834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "822e56412bd4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grade", sa.String(length=2), nullable=True))
        batch_op.add_column(
            sa.Column("class_teacher_remark", sa.String(length=300), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.drop_column("class_teacher_remark")
        batch_op.drop_column("grade")

    # ### end Alembic commands ###
